# Generated by Django 5.1.5 on 2025-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
