# Generated by Django 5.1.5 on 2025-02-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='Hi this ', max_length=150),
            preserve_default=False,
        ),
    ]
